[package]
name = "dc4"
version = "0.0.1"
authors = ["William R. Fraser <wfraser@codewise.org>"]

[dependencies]
num = "0.1"

[[bin]]
name = "dc4"
doc = false
path = "src/main.rs"

[profile.release]
lto = true
